import { Category, City, Vendor } from "./types/Vendors";

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Photographers",
    slug: "photographers",
    img: "https://cdn.naturettl.com/wp-content/uploads/2017/04/22013824/become-professional-wildlife-photographer.jpg",
    ranking: 1,
  },
  {
    id: 2,
    name: "Videographers",
    slug: "videographers",
    ranking: 7,
  },
  {
    id: 3,
    name: "Venues",
    slug: "venues",
    img: "https://howefarmstn.com/wp-content/uploads/2022/09/outdoor-ceremony_1-1024x819-1-1024x675.jpg",
    ranking: 2,
  },
  {
    id: 4,
    name: "Caterers",
    slug: "caterers",
    ranking: 9,
  },
  {
    id: 5,
    name: "Wedding Bands",
    slug: "wedding-bands",
    ranking: 12,
  },
  {
    id: 6,
    name: "DJs",
    slug: "djs",
    img: "https://cdn0.hitched.co.uk/article/9653/3_2/1280/jpg/133569-things-your-wedding-dj-wants-you-to-know-dj-knight-music.jpeg",
    ranking: 3,
  },
  {
    id: 7,
    name: "Florists",
    slug: "florists",
    ranking: 17,
  },
  {
    id: 8,
    name: "Wedding Planners",
    slug: "wedding-planners",
    ranking: 8,
  },
  {
    id: 9,
    name: "Makeup Artists",
    slug: "makeup-artists",
    img: "https://images.squarespace-cdn.com/content/v1/5a9ee2ec70e8023a569f383b/349d7d82-0fb0-4236-9f1f-64cb22fe644c/simplebeautyartistry-bridal-makeup-artist-blogbanner1.jpg",
    ranking: 6,
  },
  {
    id: 10,
    name: "Hair Stylists",
    slug: "hair-stylists",
    ranking: 10,
  },
  {
    id: 11,
    name: "Bridal Boutiques",
    slug: "bridal-boutiques",
    ranking: 11,
  },
  {
    id: 12,
    name: "Groom Wedding Dress",
    slug: "groom-wear",
    img: "https://media.istockphoto.com/id/1303804647/photo/making-sure-i-look-on-point-for-my-bride.jpg?s=612x612&w=0&k=20&c=Uj420lORCvy4w9Rz1tx1d0KO6ytbfN06DqiBBm_o1M0=",
    ranking: 4,
  },
  {
    id: 13,
    name: "Jewelers",
    slug: "jewelers",
    ranking: 13,
  },
  {
    id: 14,
    name: "Transportation",
    slug: "transportation",
    ranking: 14,
  },
  {
    id: 15,
    name: "Rentals",
    slug: "rentals",
    ranking: 15,
  },
  {
    id: 16,
    name: "Invitations",
    slug: "invitations",
    ranking: 16,
  },
  {
    id: 17,
    name: "Bridal Wedding Dress",
    slug: "favors",
    img: "https://www.brides.com/thmb/6Z_mrS1dHflEIvod_jDA21UOdks=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grace-loves-lace-landscape-b197100dc8a04bf7b060f8442fdd4f31.jpeg",
    ranking: 5,
  },
  {
    id: 18,
    name: "Travel",
    slug: "travel",
    ranking: 18,
  },
  {
    id: 19,
    name: "Honeymoon",
    slug: "honeymoon",
    ranking: 19,
  },
  {
    id: 20,
    name: "Gifts",
    slug: "gifts",
    ranking: 20,
  },
  {
    id: 21,
    name: "Health & Fitness",
    slug: "health-fitness",
    ranking: 21,
  },
  {
    id: 22,
    name: "Insurance",
    slug: "insurance",
    ranking: 22,
  },
  {
    id: 23,
    name: "Legal",
    slug: "legal",
    ranking: 23,
  },
  {
    id: 24,
    name: "Officiants",
    slug: "officiants",
    ranking: 24,
  },
  {
    id: 25,
    name: "Photo Booths",
    slug: "photo-booths",
    ranking: 25,
  },
  {
    id: 26,
    name: "Decor",
    slug: "decor",
    ranking: 26,
  },
  {
    id: 27,
    name: "Cakes",
    slug: "cakes",
    ranking: 27,
  },
  {
    id: 28,
    name: "Dance Lessons",
    slug: "dance-lessons",
    ranking: 28,
  },
  {
    id: 29,
    name: "Music",
    slug: "music",
    ranking: 29,
  },
  {
    id: 30,
    name: "Entertainment",
    slug: "entertainment",
    ranking: 30,
  },
  {
    id: 31,
    name: "Bartenders",
    slug: "bartenders",
    ranking: 31,
  },
  {
    id: 32,
    name: "Tents & Rentals",
    slug: "tents-rentals",
    ranking: 32,
  },
  {
    id: 33,
    name: "Lighting & Decor",
    slug: "lighting-decor",
    ranking: 33,
  },
  {
    id: 34,
    name: "Event Rentals",
    slug: "event-rentals",
    ranking: 34,
  },
];

export const CITIES: City[] = [
  {
    id: 1,
    name: "Athens",
    country: "Greece",
    slug: "athens",
  },
  {
    id: 2,
    name: "Thessaloniki",
    country: "Greece",
    slug: "thessaloniki",
  },
  {
    id: 3,
    name: "Patras",
    country: "Greece",
    slug: "patras",
  },
  {
    id: 4,
    name: "Heraklion",
    country: "Greece",
    slug: "heraklion",
  },
  {
    id: 5,
    name: "Larissa",
    country: "Greece",
    slug: "larissa",
  },
  {
    id: 6,
    name: "Volos",
    country: "Greece",
    slug: "volos",
  },
  {
    id: 7,
    name: "Rhodes",
    country: "Greece",
    slug: "rhodes",
  },
  {
    id: 8,
    name: "Ioannina",
    country: "Greece",
    slug: "ioannina",
  },
  {
    id: 9,
    name: "Chania",
    country: "Greece",
    slug: "chania",
  },
  {
    id: 10,
    name: "Agrinio",
    country: "Greece",
    slug: "agrinio",
  },
  {
    id: 11,
    name: "Kavala",
    country: "Greece",
    slug: "kavala",
  },
  {
    id: 12,
    name: "Kalamata",
    country: "Greece",
    slug: "kalamata",
  },
  {
    id: 13,
    name: "Trikala",
    country: "Greece",
    slug: "trikala",
  },
  {
    id: 14,
    name: "Serres",
    country: "Greece",
    slug: "serres",
  },
  {
    id: 15,
    name: "Lamia",
    country: "Greece",
    slug: "lamia",
  },
  {
    id: 16,
    name: "Alexandroupoli",
    country: "Greece",
    slug: "alexandroupoli",
  },
  {
    id: 17,
    name: "Katerini",
    country: "Greece",
    slug: "katerini",
  },
  {
    id: 18,
    name: "Mytilene",
    country: "Greece",
    slug: "mytilene",
  },
  {
    id: 19,
    name: "Kozani",
    country: "Greece",
    slug: "kozani",
  },
  {
    id: 20,
    name: "Chalkida",
    country: "Greece",
    slug: "chalkida",
  },
  {
    id: 21,
    name: "Komotini",
    country: "Greece",
    slug: "komotini",
  },
  {
    id: 22,
    name: "Rethymno",
    country: "Greece",
    slug: "rethymno",
  },
  {
    id: 23,
    name: "Pyrgos",
    country: "Greece",
    slug: "pyrgos",
  },
  {
    id: 24,
    name: "Drama",
    country: "Greece",
    slug: "drama",
  },
  {
    id: 25,
    name: "Veria",
    country: "Greece",
    slug: "veria",
  },
  {
    id: 27,
    name: "Korinthos",
    country: "Greece",
    slug: "korinthos",
  },
  {
    id: 28,
    name: "Kilkis",
    country: "Greece",
    slug: "kilkis",
  },
  {
    id: 29,
    name: "Xanthi",
    country: "Greece",
    slug: "xanthi",
  },
  {
    id: 30,
    name: "Preveza",
    country: "Greece",
    slug: "preveza",
  },
  {
    id: 33,
    name: "Chios",
    country: "Greece",
    slug: "chios",
  },
  {
    id: 34,
    name: "Kos",
    country: "Greece",
    slug: "kos",
  },
];

export const VENDORS: Vendor[] = [
  {
    id: 1,
    name: "The Grand Wedding Hall",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "the-grand-wedding-hall",
  },
  {
    id: 2,
    name: "Elegant Garden Weddings",
    cityId: 2,
    categoryId: 2,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "elegant-garden-weddings",
  },
  {
    id: 3,
    name: "Romantic Beach Weddings",
    cityId: 3,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "romantic-beach-weddings",
  },
  {
    id: 4,
    name: "Luxury Villa Weddings",
    cityId: 4,
    categoryId: 4,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "luxury-villa-weddings",
  },
  {
    id: 5,
    name: "Rustic Barn Weddings",
    cityId: 5,
    categoryId: 5,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "rustic-barn-weddings",
  },
  {
    id: 6,
    name: "Enchanted Forest Weddings",
    cityId: 6,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "enchanted-forest-weddings",
  },
  {
    id: 7,
    name: "Glamorous Ballroom Weddings",
    cityId: 7,
    categoryId: 7,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "glamorous-ballroom-weddings",
  },
  {
    id: 8,
    name: "Modern Rooftop Weddings",
    cityId: 8,
    categoryId: 8,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "modern-rooftop-weddings",
  },
  {
    id: 9,
    name: "Intimate Garden Weddings",
    cityId: 9,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "intimate-garden-weddings",
  },
  {
    id: 10,
    name: "Historic Mansion Weddings",
    cityId: 10,
    categoryId: 10,
    img: "/images/no-image.png",
    rating: 4.7,
    slug: "historic-mansion-weddings",
  },
  {
    id: 11,
    name: "Charming Chapel Weddings",
    cityId: 11,
    categoryId: 11,
    img: "/images/no-image.png",
    rating: 4.4,
    slug: "charming-chapel-weddings",
  },
  {
    id: 12,
    name: "Industrial Warehouse Weddings",
    cityId: 12,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 3.4,
    slug: "industrial-warehouse-weddings",
  },
  {
    id: 13,
    name: "Seaside Resort Weddings",
    cityId: 13,
    categoryId: 13,
    img: "/images/no-image.png",
    rating: 4.6,
    slug: "seaside-resort-weddings",
  },
  {
    id: 14,
    name: "Elegant Garden Weddings",
    cityId: 14,
    categoryId: 14,
    img: "/images/no-image.png",
    rating: 3.3,
    slug: "elegant-garden-weddings",
  },
  {
    id: 15,
    name: "Intimate Garden Weddings",
    cityId: 15,
    categoryId: 15,
    img: "/images/no-image.png",
    rating: 4.8,
    slug: "intimate-garden-weddings",
  },
  {
    id: 16,
    name: "Rustic Barn Weddings",
    cityId: 16,
    categoryId: 16,
    img: "/images/no-image.png",
    rating: 3.2,
    slug: "rustic-barn-weddings",
  },
  {
    id: 17,
    name: "Glamorous Ballroom Weddings",
    cityId: 17,
    categoryId: 17,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "glamorous-ballroom-weddings",
  },
  {
    id: 18,
    name: "Enchanted Forest Weddings",
    cityId: 18,
    categoryId: 18,
    img: "/images/no-image.png",
    rating: 3.1,
    slug: "enchanted-forest-weddings",
  },
  {
    id: 19,
    name: "Romantic Beach Weddings",
    cityId: 19,
    categoryId: 19,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "romantic-beach-weddings",
  },
  {
    id: 20,
    name: "Elegant Garden Weddings",
    cityId: 20,
    categoryId: 20,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "elegant-garden-weddings",
  },
  {
    id: 21,
    name: "The Grand Wedding Hall",
    cityId: 21,
    categoryId: 21,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "the-grand-wedding-hall",
  },
  {
    id: 22,
    name: "Modern Rooftop Weddings",
    cityId: 22,
    categoryId: 22,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "modern-rooftop-weddings",
  },
  {
    id: 23,
    name: "Cyberdyne Systems",
    cityId: 23,
    categoryId: 23,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "cyberdyne-systems",
  },
  {
    id: 23,
    name: "Cyberdyne Systems",
    cityId: 23,
    categoryId: 23,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "cyberdyne-systems",
  },
  {
    id: 25,
    name: "Stark Industries",
    cityId: 25,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "stark-industries",
  },
  {
    id: 26,
    name: "Acme Corporation",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "acme-corporation",
  },
  {
    id: 27,
    name: "Globex Industries",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "globex-industries",
  },
  {
    id: 28,
    name: "Initech",
    cityId: 3,
    categoryId: 5,
    img: "/images/no-image.png",
    rating: 4.4,
    slug: "initech",
  },
  {
    id: 34,
    name: "Umbrella Corporation",
    cityId: 9,
    categoryId: 4,
    img: "/images/no-image.png",
    rating: 3.3,
    slug: "umbrella-corporation",
  },
  {
    id: 35,
    name: "Globex Industries",
    cityId: 10,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.7,
    slug: "globex-industries",
  },
  {
    id: 36,
    name: "Acme Corporation",
    cityId: 11,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.2,
    slug: "acme-corporation",
  },
  {
    id: 37,
    name: "Initech",
    cityId: 12,
    categoryId: 2,
    img: "/images/no-image.png",
    rating: 4.6,
    slug: "initech",
  },
  {
    id: 38,
    name: "Abstergo Industries",
    cityId: 13,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.1,
    slug: "abstergo-industries",
  },
  {
    id: 39,
    name: "Umbrella Corporation",
    cityId: 14,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "umbrella-corporation",
  },
  {
    id: 40,
    name: "Weyland-Yutani Corporation",
    cityId: 15,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "weyland-yutani-corporation",
  },
  {
    id: 41,
    name: "Saints & Sinners Wedding Hall",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.0,
    slug: "saints-sinners-wedding-hall",
  },
  {
    id: 42,
    name: "Aspasias Wedding Hall",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "aspasias-wedding-hall",
  },
  {
    id: 43,
    name: "Pelagia's Wedding Hall",
    categoryId: 3,
    cityId: 1,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "pelagias-wedding-hall",
  },
  {
    id: 44,
    name: "Anna's Wedding Hall",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "annas-wedding-hall",
  },
  {
    id: 45,
    name: "Nonantum Resort",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "nonantum-resort",
  },
  {
    id: 46,
    name: "Vendor 6",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "vendor-6",
  },
  {
    id: 47,
    name: "Vendor 7",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "vendor-7",
  },
  {
    id: 48,
    name: "Vendor 8",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "vendor-8",
  },
  {
    id: 49,
    name: "Vendor 9",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "vendor-9",
  },
  {
    id: 50,
    name: "Vendor 10",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "vendor-10",
  },
];
