import { Category, City, Vendor } from "./types/Vendors";

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Venues",
    slug: "venues",
    img: "https://howefarmstn.com/wp-content/uploads/2022/09/outdoor-ceremony_1-1024x819-1-1024x675.jpg",
    ranking: 1,
  },
  {
    id: 2,
    name: "Wedding Dress",
    slug: "favors",
    img: "https://www.brides.com/thmb/6Z_mrS1dHflEIvod_jDA21UOdks=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grace-loves-lace-landscape-b197100dc8a04bf7b060f8442fdd4f31.jpeg",
    ranking: 2,
  },
  {
    id: 3,
    name: "Suits & Tuxedos",
    slug: "suits",
    img: "https://media.istockphoto.com/id/1303804647/photo/making-sure-i-look-on-point-for-my-bride.jpg?s=612x612&w=0&k=20&c=Uj420lORCvy4w9Rz1tx1d0KO6ytbfN06DqiBBm_o1M0=",
    ranking: 3,
  },
  {
    id: 4,
    name: "Jewelers",
    slug: "jewelers",
    img: "https://www.varoujan.com.au/wp-content/uploads/2022/05/sandy-millar-8vaQKYnawHw-unsplash-scaled.jpg",
    ranking: 4,
  },
  {
    id: 5,
    name: "Photographers",
    slug: "photographers",
    img: "https://cdn.naturettl.com/wp-content/uploads/2017/04/22013824/become-professional-wildlife-photographer.jpg",
    ranking: 5,
  },
  {
    id: 6,
    name: "Videographers",
    slug: "videographers",
    img: "https://assets-global.website-files.com/5fac161927bf86485ba43fd0/64c667d806a56caeed90d213_Blog%20Cover_2023_07_Video%20Portfolio%20Guide_%20Best%20Examples%20for%20Editors%20_%20Videographers%20(1).webp",
    ranking: 6,
  },
  {
    id: 7,
    name: "DJs",
    slug: "djs",
    img: "https://cdn0.hitched.co.uk/article/9653/3_2/1280/jpg/133569-things-your-wedding-dj-wants-you-to-know-dj-knight-music.jpeg",
    ranking: 7,
  },
  {
    id: 8,
    name: "Caterers",
    slug: "caterers",
    img: "https://www.happybaliwedding.com/wp-content/uploads/2017/08/Cost-of-Bali-Wedding-Catering.jpg",
    ranking: 8,
  },
  {
    id: 9,
    name: "Florists",
    slug: "florists",
    img: "https://fiftyflowers.com/cdn/shop/articles/wedding-flower-list-who-gets-flowers_1100x.png?v=1640288395",
    ranking: 9,
  },
  {
    id: 10,
    name: "Beauty",
    slug: "beauty",
    img: "https://images.squarespace-cdn.com/content/v1/5a9ee2ec70e8023a569f383b/349d7d82-0fb0-4236-9f1f-64cb22fe644c/simplebeautyartistry-bridal-makeup-artist-blogbanner1.jpg",
    ranking: 10,
  },
  {
    id: 11,
    name: "Music Bands",
    slug: "music-bands",
    img: "https://cdn0.hitched.co.uk/article/7384/3_2/960/jpg/34837-sound-generation-Qs-to-ask-your-wedding-band-and-dj-fdf463e.jpeg",
    ranking: 11,
  },
  {
    id: 12,
    name: "Wedding Planners",
    slug: "wedding-planners",
    img: "https://www.moltobellaweddings.com/wp-content/uploads/2019/05/Wedding-Planner.jpg",
    ranking: 12,
  },
  {
    id: 13,
    name: "Wedding Cakes",
    slug: "wedding-cakes",
    img: "https://cdn0.weddingwire.com/vendor/998384/3_2/640/jpg/lytle-hotel-cincinnati-wedding-cake_51_483899-171518878619645.webp",
    ranking: 13,
  },
  {
    id: 14,
    name: "Bar services",
    slug: "bar-services",
    img: "https://149385730.v2.pressablecdn.com/wp-content/uploads/2022/04/celebrate-wedding-party-bartending-services-elevater-wedding-reception_05.jpg",
    ranking: 14,
  },
  {
    id: 15,
    name: "Dance Lessons",
    slug: "dance-lessons",
    img: "https://www.phillymag.com/wp-content/uploads/sites/3/2019/05/dancelessons-Kanayo-Adibe-featured.jpg",
    ranking: 15,
  },
  {
    id: 16,
    name: "Decor",
    slug: "decor",
    img: "https://hctg-images.imgix.net/images/venues/black-gold-golf-club/20230613BlackGoldGolfClub05.jpg?auto=format%2Ccompress&fit=clamp&h=430&s=cbba964c7d67710c2807fb9d6e10ac07",
    ranking: 16,
  },
  {
    id: 17,
    name: "Favors & Gifts",
    slug: "favors-and-gifts",
    img: "https://rusticandmain.com/cdn/shop/articles/596df2c64e639fc24c60a18a75045312_800x.jpg?v=1680814332",
    ranking: 17,
  },
  {
    id: 18,
    name: "Invitations",
    slug: "invitations",
    img: "https://images.squarespace-cdn.com/content/v1/5b4bac75620b854a7b70a12c/1595357797205-KJNBV9GSE670MF8F6JA6/Leslie05_Custom_HuntWrightDesignCo.",
    ranking: 18,
  },
  {
    id: 19,
    name: "Photo Booths",
    slug: "photo-booths",
    img: "https://cdn0.weddingwire.com/vendor/821489/3_2/960/jpg/1518582822-852129fc7eda01d8-1518582820-7eeefd43ce62443a-1518582807718-6-wedding_photo_boot.jpeg",
    ranking: 19,
  },
  {
    id: 20,
    name: "Transportation",
    slug: "transportation",
    img: "https://drivenglobalusa.com/wp-content/uploads/2019/06/wedding-transportation-service-Raleigh-Durham-Morrisville-Cary-Chapel-Hill-Wake-Forest-Nort-Hills-Smithfield-Clayton-Garner-Angier-Goldsboro-Fuquay-Varina-Carrboro-RDU.jpg",
    ranking: 20,
  },
];

export const CITIES: City[] = [
  {
    id: 1,
    name: "Athens",
    country: "Greece",
    slug: "athens",
  },
  {
    id: 2,
    name: "Thessaloniki",
    country: "Greece",
    slug: "thessaloniki",
  },
  {
    id: 3,
    name: "Patras",
    country: "Greece",
    slug: "patras",
  },
  {
    id: 4,
    name: "Heraklion",
    country: "Greece",
    slug: "heraklion",
  },
  {
    id: 5,
    name: "Larissa",
    country: "Greece",
    slug: "larissa",
  },
  {
    id: 6,
    name: "Volos",
    country: "Greece",
    slug: "volos",
  },
  {
    id: 7,
    name: "Rhodes",
    country: "Greece",
    slug: "rhodes",
  },
  {
    id: 8,
    name: "Ioannina",
    country: "Greece",
    slug: "ioannina",
  },
  {
    id: 9,
    name: "Chania",
    country: "Greece",
    slug: "chania",
  },
  {
    id: 10,
    name: "Agrinio",
    country: "Greece",
    slug: "agrinio",
  },
  {
    id: 11,
    name: "Kavala",
    country: "Greece",
    slug: "kavala",
  },
  {
    id: 12,
    name: "Kalamata",
    country: "Greece",
    slug: "kalamata",
  },
  {
    id: 13,
    name: "Trikala",
    country: "Greece",
    slug: "trikala",
  },
  {
    id: 14,
    name: "Serres",
    country: "Greece",
    slug: "serres",
  },
  {
    id: 15,
    name: "Lamia",
    country: "Greece",
    slug: "lamia",
  },
  {
    id: 16,
    name: "Alexandroupoli",
    country: "Greece",
    slug: "alexandroupoli",
  },
  {
    id: 17,
    name: "Katerini",
    country: "Greece",
    slug: "katerini",
  },
  {
    id: 18,
    name: "Mytilene",
    country: "Greece",
    slug: "mytilene",
  },
  {
    id: 19,
    name: "Kozani",
    country: "Greece",
    slug: "kozani",
  },
  {
    id: 20,
    name: "Chalkida",
    country: "Greece",
    slug: "chalkida",
  },
  {
    id: 21,
    name: "Komotini",
    country: "Greece",
    slug: "komotini",
  },
  {
    id: 22,
    name: "Rethymno",
    country: "Greece",
    slug: "rethymno",
  },
  {
    id: 23,
    name: "Pyrgos",
    country: "Greece",
    slug: "pyrgos",
  },
  {
    id: 24,
    name: "Drama",
    country: "Greece",
    slug: "drama",
  },
  {
    id: 25,
    name: "Veria",
    country: "Greece",
    slug: "veria",
  },
  {
    id: 27,
    name: "Korinthos",
    country: "Greece",
    slug: "korinthos",
  },
  {
    id: 28,
    name: "Kilkis",
    country: "Greece",
    slug: "kilkis",
  },
  {
    id: 29,
    name: "Xanthi",
    country: "Greece",
    slug: "xanthi",
  },
  {
    id: 30,
    name: "Preveza",
    country: "Greece",
    slug: "preveza",
  },
  {
    id: 33,
    name: "Chios",
    country: "Greece",
    slug: "chios",
  },
  {
    id: 34,
    name: "Kos",
    country: "Greece",
    slug: "kos",
  },
];

export const VENDORS: Vendor[] = [
  {
    id: 1,
    name: "The Grand Wedding Hall",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "the-grand-wedding-hall",
  },
  {
    id: 2,
    name: "Elegant Garden Weddings",
    cityId: 2,
    categoryId: 2,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "elegant-garden-weddings",
  },
  {
    id: 3,
    name: "Romantic Beach Weddings",
    cityId: 3,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "romantic-beach-weddings",
  },
  {
    id: 4,
    name: "Luxury Villa Weddings",
    cityId: 4,
    categoryId: 4,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "luxury-villa-weddings",
  },
  {
    id: 5,
    name: "Rustic Barn Weddings",
    cityId: 5,
    categoryId: 5,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "rustic-barn-weddings",
  },
  {
    id: 6,
    name: "Enchanted Forest Weddings",
    cityId: 6,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "enchanted-forest-weddings",
  },
  {
    id: 7,
    name: "Glamorous Ballroom Weddings",
    cityId: 7,
    categoryId: 7,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "glamorous-ballroom-weddings",
  },
  {
    id: 8,
    name: "Modern Rooftop Weddings",
    cityId: 8,
    categoryId: 8,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "modern-rooftop-weddings",
  },
  {
    id: 9,
    name: "Intimate Garden Weddings",
    cityId: 9,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "intimate-garden-weddings",
  },
  {
    id: 10,
    name: "Historic Mansion Weddings",
    cityId: 10,
    categoryId: 10,
    img: "/images/no-image.png",
    rating: 4.7,
    slug: "historic-mansion-weddings",
  },
  {
    id: 11,
    name: "Charming Chapel Weddings",
    cityId: 11,
    categoryId: 11,
    img: "/images/no-image.png",
    rating: 4.4,
    slug: "charming-chapel-weddings",
  },
  {
    id: 12,
    name: "Industrial Warehouse Weddings",
    cityId: 12,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 3.4,
    slug: "industrial-warehouse-weddings",
  },
  {
    id: 13,
    name: "Seaside Resort Weddings",
    cityId: 13,
    categoryId: 13,
    img: "/images/no-image.png",
    rating: 4.6,
    slug: "seaside-resort-weddings",
  },
  {
    id: 14,
    name: "Elegant Garden Weddings",
    cityId: 14,
    categoryId: 14,
    img: "/images/no-image.png",
    rating: 3.3,
    slug: "elegant-garden-weddings",
  },
  {
    id: 15,
    name: "Intimate Garden Weddings",
    cityId: 15,
    categoryId: 15,
    img: "/images/no-image.png",
    rating: 4.8,
    slug: "intimate-garden-weddings",
  },
  {
    id: 16,
    name: "Rustic Barn Weddings",
    cityId: 16,
    categoryId: 16,
    img: "/images/no-image.png",
    rating: 3.2,
    slug: "rustic-barn-weddings",
  },
  {
    id: 17,
    name: "Glamorous Ballroom Weddings",
    cityId: 17,
    categoryId: 17,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "glamorous-ballroom-weddings",
  },
  {
    id: 18,
    name: "Enchanted Forest Weddings",
    cityId: 18,
    categoryId: 18,
    img: "/images/no-image.png",
    rating: 3.1,
    slug: "enchanted-forest-weddings",
  },
  {
    id: 19,
    name: "Romantic Beach Weddings",
    cityId: 19,
    categoryId: 19,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "romantic-beach-weddings",
  },
  {
    id: 20,
    name: "Elegant Garden Weddings",
    cityId: 20,
    categoryId: 20,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "elegant-garden-weddings",
  },
  {
    id: 21,
    name: "The Grand Wedding Hall",
    cityId: 21,
    categoryId: 21,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "the-grand-wedding-hall",
  },
  {
    id: 22,
    name: "Modern Rooftop Weddings",
    cityId: 22,
    categoryId: 22,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "modern-rooftop-weddings",
  },
  {
    id: 23,
    name: "Cyberdyne Next",
    cityId: 23,
    categoryId: 23,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "cyberdyne-next",
  },
  {
    id: 23,
    name: "Cyberdyne Systems",
    cityId: 23,
    categoryId: 23,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "cyberdyne-systems",
  },
  {
    id: 25,
    name: "Stark Industries",
    cityId: 25,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "stark-industries",
  },
  {
    id: 26,
    name: "Acme Corporation",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "acme-corporation",
  },
  {
    id: 27,
    name: "Globex Industries",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "globex-industries",
  },
  {
    id: 28,
    name: "Initech-x",
    cityId: 3,
    categoryId: 5,
    img: "/images/no-image.png",
    rating: 4.4,
    slug: "initech-x",
  },
  {
    id: 34,
    name: "Umbrella Corporation",
    cityId: 9,
    categoryId: 4,
    img: "/images/no-image.png",
    rating: 3.3,
    slug: "umbrella-corporation",
  },
  {
    id: 35,
    name: "Globe Industries",
    cityId: 10,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.7,
    slug: "globe-industries",
  },
  {
    id: 36,
    name: "Came Corporation",
    cityId: 11,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.2,
    slug: "came-corporation",
  },
  {
    id: 37,
    name: "Initech",
    cityId: 12,
    categoryId: 2,
    img: "/images/no-image.png",
    rating: 4.6,
    slug: "initech",
  },
  {
    id: 38,
    name: "Abstergo Industries",
    cityId: 13,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.1,
    slug: "abstergo-industries",
  },
  {
    id: 39,
    name: "Umbrella Corporation",
    cityId: 14,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 4.5,
    slug: "umbrella-corporation",
  },
  {
    id: 40,
    name: "Weyland-Yutani Corporation",
    cityId: 15,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "weyland-yutani-corporation",
  },
  {
    id: 41,
    name: "Saints & Sinners Wedding Hall",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.0,
    slug: "saints-sinners-wedding-hall",
  },
  {
    id: 42,
    name: "Aspasias Wedding Hall",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "aspasias-wedding-hall",
  },
  {
    id: 43,
    name: "Pelagia's Wedding Hall",
    categoryId: 3,
    cityId: 1,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "pelagias-wedding-hall",
  },
  {
    id: 44,
    name: "Anna's Wedding Hall",
    cityId: 1,
    categoryId: 1,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "annas-wedding-hall",
  },
  {
    id: 45,
    name: "Nonantum Resort",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "nonantum-resort",
  },
  {
    id: 46,
    name: "Nantia Resort",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "nantia-resort",
  },
  {
    id: 47,
    name: "Ktima Ragoulis",
    cityId: 1,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "ktima-ragoulis",
  },
  {
    id: 48,
    name: "Ktima Kourou",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "ktima-kourou",
  },
  {
    id: 49,
    name: "Anatoli Resort",
    cityId: 2,
    categoryId: 3,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "anatoli-resort",
  },
  {
    id: 50,
    name: "Saladino's Cloting",
    cityId: 2,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "saladinos-clothing",
  },
  {
    id: 51,
    name: "Pratt Abbott Garment Care",
    cityId: 3,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "pratt-abbott-garment-care",
  },
  {
    id: 52,
    name: "Flannel & Barrel",
    cityId: 4,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 3.9,
    slug: "flannel-barrel",
  },
  {
    id: 53,
    name: "Vendor 13",
    cityId: 5,
    categoryId: 12,
    img: "/images/no-image.png",
    rating: 4.1,
    slug: "vendor-13",
  },
  {
    id: 54,
    name: "Vendor 14",
    cityId: 6,
    categoryId: 17,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "vendor-14",
  },
  {
    id: 55,
    name: "Vendor 15",
    cityId: 7,
    categoryId: 17,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "vendor-15",
  },
  {
    id: 56,
    name: "Vendor 16",
    cityId: 8,
    categoryId: 17,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "vendor-16",
  },
  {
    id: 57,
    name: "Vendor 17",
    cityId: 9,
    categoryId: 10,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "vendor-17",
  },
  {
    id: 58,
    name: "Beautiful Hair",
    cityId: 10,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "beautifyl-hair",
  },
  {
    id: 59,
    name: "About Face",
    cityId: 11,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "about-face",
  },
  {
    id: 60,
    name: "Top Beauty",
    cityId: 12,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "top-beauty",
  },
  {
    id: 61,
    name: "Luscious Locks",
    cityId: 1,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "luscious-locks",
  },
  {
    id: 62,
    name: "Top Beauty Salon",
    cityId: 1,
    categoryId: 9,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "top-beauty-salon",
  },
  {
    id: 63,
    name: "John Stathis",
    cityId: 2,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "john-stathis",
  },
  {
    id: 64,
    name: "K Run",
    cityId: 3,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 3.7,
    slug: "k-run",
  },
  {
    id: 65,
    name: "Stelios K",
    cityId: 4,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 4.3,
    slug: "stelios-k",
  },
  {
    id: 66,
    name: "Bobby S",
    cityId: 5,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 3.6,
    slug: "bobby-s",
  },
  {
    id: 67,
    name: "James NS",
    cityId: 1,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 4.0,
    slug: "james-ns",
  },
  {
    id: 68,
    name: "Rena KLMT",
    cityId: 7,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 3.8,
    slug: "rena-klmt",
  },
  {
    id: 69,
    name: "Giorgis Sara",
    cityId: 8,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 4.2,
    slug: "giorgis-sara",
  },
  {
    id: 70,
    name: "Sandy Eleonore",
    cityId: 1,
    categoryId: 6,
    img: "/images/no-image.png",
    rating: 3.5,
    slug: "sandy-eleonore",
  },
];
