import type { Metadata } from "next";
import { Inter, Slabo_27px, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const slabo = Slabo_27px({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-slabo",
});

const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen ${roboto.className}`}>
        <Header />
        <div className="">{children}</div>
        <Footer /> 
      </body>
    </html>
  );
}
